<template>
  <svg
    height="1em"
    viewBox="0 0 24 24"
    width="1em"
    xmlns="http://www.w3.org/2000/svg"
  >
    <g
      fill="none"
      stroke="currentColor"
      stroke-linecap="round"
      stroke-linejoin="round"
      stroke-width="2"
    >
      <path d="M12 19v1M19 12h1M12 5v-1M5 12h-1" stroke-dasharray="2" stroke-dashoffset="2">
        <animate
          attributeName="d"
          begin="0.6s"
          dur="0.2s"
          fill="freeze"
          values="M12 19v1M19 12h1M12 5v-1M5 12h-1;M12 21v1M21 12h1M12 3v-1M3 12h-1"
        />
        <animate
          attributeName="stroke-dashoffset"
          begin="0.6s"
          dur="0.2s"
          fill="freeze"
          values="2;0"
        />
      </path>
      <path d="M17 17l0.5 0.5M17 7l0.5 -0.5M7 7l-0.5 -0.5M7 17l-0.5 0.5" stroke-dasharray="2" stroke-dashoffset="2">
        <animate
          attributeName="d"
          begin="0.8s"
          dur="0.2s"
          fill="freeze"
          values="M17 17l0.5 0.5M17 7l0.5 -0.5M7 7l-0.5 -0.5M7 17l-0.5 0.5;M18.5 18.5l0.5 0.5M18.5 5.5l0.5 -0.5M5.5 5.5l-0.5 -0.5M5.5 18.5l-0.5 0.5"
        />
        <animate
          attributeName="stroke-dashoffset"
          begin="0.8s"
          dur="0.2s"
          fill="freeze"
          values="2;0"
        />
      </path>
      <animateTransform
        attributeName="transform"
        dur="30s"
        repeatCount="indefinite"
        type="rotate"
        values="0 12 12;360 12 12"
      />
    </g>
    <mask id="SVGu6kfobeu">
      <circle
        cx="12"
        cy="12"
        fill="#fff"
        r="12"
      />
      <circle
        cx="18"
        cy="6"
        fill="#fff"
        r="12"
      >
        <animate
          attributeName="cx"
          dur="0.4s"
          fill="freeze"
          values="18;22"
        />
        <animate
          attributeName="cy"
          dur="0.4s"
          fill="freeze"
          values="6;2"
        />
        <animate
          attributeName="r"
          dur="0.4s"
          fill="freeze"
          values="12;3"
        />
      </circle>
      <circle cx="18" cy="6" r="10">
        <animate
          attributeName="cx"
          dur="0.4s"
          fill="freeze"
          values="18;22"
        />
        <animate
          attributeName="cy"
          dur="0.4s"
          fill="freeze"
          values="6;2"
        />
        <animate
          attributeName="r"
          dur="0.4s"
          fill="freeze"
          values="10;1"
        />
      </circle>
    </mask>
    <circle
      cx="12"
      cy="12"
      fill="currentColor"
      mask="url(#SVGu6kfobeu)"
      r="10"
    >
      <animate
        attributeName="r"
        dur="0.4s"
        fill="freeze"
        values="10;6"
      />
    </circle>
  </svg>
</template>
