packages:
  - 'apps/*'
  - 'packages/*'
  - 'packages/configs/*'

catalog:
  '@types/lodash-es': '^4.17.12'
  '@types/node': '^24.0.10'
  lodash-es: '^4.17.21'
  picocolors: '^1.1.1'
  vite: '^7.0.2'
  vite-plugin-compression: '^0.5.1'
  vite-plugin-vue-devtools: '^7.7.7'
  vitepress: '^1.6.3'
  vue: '^3.5.17'
  turbo: ^2.5.4
  unbuild: '^3.5.0'

  # lint
  prettier: '^3.6.2'
  eslint: '^9.30.1'
