packages:
  - docs
  - packages/*
  - packages/configs/*

catalog:
  '@biomejs/biome': ^2.2.4
  '@types/lodash-es': ^4.17.12
  '@types/node': ^24.3.3
  '@vueuse/core': ^13.9.0
  eslint: ^9.35.0
  lint-staged: ^16.1.6
  lodash-es: ^4.17.21
  motion-v: ^1.7.1
  ora: ^8.2.0
  picocolors: ^1.1.1
  prompts: ^2.4.2
  turbo: ^2.5.6
  unbuild: ^3.6.1
  unocss: ^66.5.1
  vite: ^7.1.5
  vite-plugin-compression: ^0.5.1
  vite-plugin-vue-devtools: ^8.0.2
  vitepress: ^1.6.4
  vue: ^3.5.21
  iconify-icon: ^3.0.1

ignoredBuiltDependencies:
  - esbuild
