packages:
  - docs
  - packages/*
  - packages/configs/*

catalog:
  '@biomejs/biome': ^2.2.4
  '@types/node': ^24.5.2
  eslint: ^9.36.0
  iconify-icon: ^3.0.1
  lint-staged: ^16.2.1
  motion-v: ^1.7.1
  ora: ^9.0.0
  picocolors: ^1.1.1
  prompts: ^2.4.2
  turbo: ^2.5.8
  unbuild: ^3.6.1
  unocss: ^66.5.2
  vite: ^7.1.7
  vite-plugin-compression: ^0.5.1
  vite-plugin-vue-devtools: 7.7.7
  vitepress: ^1.6.4
  vue: ^3.5.22

ignoredBuiltDependencies:
  - esbuild
