packages:
  - docs
  - packages/*
  - packages/configs/*

catalog:
  '@biomejs/biome': ^2.2.2
  '@types/lodash-es': ^4.17.12
  '@types/node': ^24.3.0
  eslint: ^9.34.0
  lint-staged: ^16.1.5
  lodash-es: ^4.17.21
  picocolors: ^1.1.1
  turbo: ^2.5.6
  unbuild: ^3.6.1
  unocss: ^66.5.0
  vite: ^7.1.3
  vite-plugin-compression: ^0.5.1
  vite-plugin-vue-devtools: ^8.0.1
  vitepress: ^1.6.4
  vue: ^3.5.20
